### ISSUE TITLE
.config.env not work

### ISSUE THREAD

**Issue by serical** [arthurgeek/vaultwarden-fly-template#15]
for example: I set ADMIN_TOKEN
```
# https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page
ADMIN_TOKEN=xxxxxx
```
<img width="725" alt="image" src="https://github.com/arthurgeek/vaultwarden-fly-template/assets/8707532/911d00bf-db06-4856-b55b-90c72004cee6">

**Comment by arthurgeek** [comment]
Can you run `task fly:secrets:set` and see if it works? This will run the following command: https://github.com/arthurgeek/vaultwarden-fly-template/blob/main/.taskfiles/fly/secrets.yaml#L7

**Comment by arthurgeek** [comment]
I also just added the command above to run before any (local) deployments and a new FAQ here: https://github.com/arthurgeek/vaultwarden-fly-template/commit/07309b1633ff1aaf88d279e321a298316a312dbe.

**Comment by serical** [comment]
I delete all apps in fly.io, and deploy again, and I get a blank web page,  maybe something in `secrets` cause this, because the `secrets` is not exists on my first deploy

<img width="1328" alt="image" src="https://github.com/arthurgeek/vaultwarden-fly-template/assets/8707532/b742327c-15c3-43f5-9f65-a5c48b38cd68">

a blank web page
<img width="696" alt="image" src="https://github.com/arthurgeek/vaultwarden-fly-template/assets/8707532/8a5644d7-bfc4-44c1-9ea8-300bab31f4f8">

**Comment by arthurgeek** [comment]
Yes, the secrets wouldn't exist in the first deployment if made before previously mentioned commit. This was fixed yesterday. If you updated the template after the commit above, everything should work. You can also run the command I mentioned, it should work even without yesterday's commit.

**Comment by arthurgeek** [comment]
Closing as stale. Please reopen in case it's still not working.
